env: local

spring:
  application:
    name: cinema
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
    hikari:
      schema: cinema
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: cinema
    database-platform: org.hibernate.dialect.PostgreSQLDialect

PGSQL_SERVICE_SCHEMA: ${spring.jpa.properties.hibernate.default_schema}

logging:
  level:
    root: INFO
    "org.hibernate.SQL": DEBUG
    "org.hibernate.type.descriptor.sql.BasicBinder": TRACE
    "org.hibernate.orm.jdbc.bind": TRACE

spring.cloud.config.enabled: false
eureka:
  client:
    enabled: false
server:
  port: 8080
